<template lang="md">
  ## Amazon Rainforest Dieback

  The Amazon rainforest is the largest tropical rainforest and a center of biodiversity, that is defined by plenty of rainfall, mostly generated by itself.<SourceAnchorLink to-id="44" /> A moist atmosphere is being upheld by high temperatures. These cause evaporation of local rainfall and transpiration of moisture from plant leaves, basically creating more rainfall.<SourceAnchorLink to-id="2" />

  ![Amazon Rainforest Dieback](~assets/gif/amzn.gif)

  <span id="h-AMZN-output-1" class="is-highlightable">The rainforest absorbs great amounts of carbon and cools the global temperature.<SourceAnchorLink to-id="45" /> “Even a partial loss of rainforest would substantially increase carbon levels in the atmosphere.”<SourceAnchorLink to-id="46" /></span> Increasing global temperatures provoke a decrease in rainfall, leading to a reduction in evaporation. This only amplifies tropical warming and drying.<SourceAnchorLink to-id="47" /> <span id="h-AMZN-input-2" class="is-highlightable">Additionally transpiration declines as a result of higher CO2 levels that leaves plant pores open less widely.</span> <span id="h-AMZN-output-3" class="is-highlightable">By doing so the plants lose less water and therefore transfer less water into the atmosphere.<SourceAnchorLink to-id="2" /></span> <span id="h-AMZN-input-1" class="is-highlightable">Another factor is deforestation, as a decline in trees negatively impacts evaporation and reduces rainfall significantly.<SourceAnchorLink to-id="47" /></span>

  <span id="h-AMZN-output-4" class="is-highlightable">Eventually all these events entail less fertile tropical soil and result in and/or are caused by tree loss.</span> <span id="h-AMZN-output-0" class="is-highlightable">Continuing the current path of deforestation, a projected trend shows that 40% of Amazon forests will be eliminated by 2050.</span> <span id="h-AMZN-output-2" class="is-highlightable">As a result a vast release of carbon and drier climate would occur.<SourceAnchorLink to-id="48" /> There have already been noticeable consequences like severe droughts in 2005 and 2010</span> <span id="h-AMZN-input-0" class="is-highlightable">as well as an increase in wildfires.<SourceAnchorLink to-id="49" /></span> Dry seasons have grown during the past decades. And it has been suggested that an excessive dry period represents a tipping point for the Amazon rainforest, turning it into a completely different habitat.<SourceAnchorLink to-id="46" />

  Research ”[...] shows that even severe cuts in deforestation and carbon emissions will fail to save the emblematic South American jungle [...]” and that “[...] the destruction of large parts of the forest is "irreversible"”.<SourceAnchorLink to-id="50" />
</template>

<script>
import SourceAnchorLink from '~/components/BaseSourceAnchorLink.vue'

export default {
  components: {
    SourceAnchorLink
  },

  mounted() {
    this.$nextTick(function() {
      this.$emit('isReady')
    })
  }
}
</script>
