<template lang="md">
  ## Amazon Forest Dieback

  The Amazon rainforest is the largest tropical rainforest and a center of biodiversity, that is defined by plenty of rainfall, mostly generated by itself.<SourceAnchorLink to-id="47" /> A moist atmosphere is being upheld by high temperatures. These cause evaporation of local rainfall and transpiration of moisture from plant leaves, basically creating more rainfall.<SourceAnchorLink to-id="1" />

  The rainforest absorbs great amounts of carbon and cools the global temperature.<SourceAnchorLink to-id="48" /> “Even a partial loss of rainforest would substantially increase carbon levels in the atmosphere.”<SourceAnchorLink to-id="49" /> Increasing global temperatures provoke a decrease in rainfall, leading to a reduction in evaporation. This only amplifies tropical warming and drying.<SourceAnchorLink to-id="50" /> Additionally transpiration declines as a result of higher CO2 levels that leaves plant pores open less widely. By doing so the plants lose less water and therefore transfer less water into the atmosphere.<SourceAnchorLink to-id="1" /> Another factor is deforestation, as a decline in trees negatively impacts evaporation and reduces rainfall significantly.<SourceAnchorLink to-id="50" />

  Eventually all these events entail less fertile tropical soil and result in and/or are caused by tree loss. Continuing the current path of deforestation, a projected trend shows that 40% of Amazon forests will be eliminated by 2050. As a result a vast release of carbon and drier climate would occur.<SourceAnchorLink to-id="51" />

  There have already been noticeable consequences like severe droughts in 2005 and 2010 as well as an increase in wildfires.<SourceAnchorLink to-id="52" /> Dry seasons have grown during the past decades. And it has been suggested that an excessive dry period represents a tipping point for the Amazon rainforest, turning it into a completely different habitat.<SourceAnchorLink to-id="49" />

  Research ”[...] shows that even severe cuts in deforestation and carbon emissions will fail to save the emblematic South American jungle [...]” and that “[...] the destruction of large parts of the forest is "irreversible"”.<SourceAnchorLink to-id="53" />
</template>

<script>
import SourceAnchorLink from '~/components/BaseSourceAnchorLink.vue'

export default {
  components: {
    SourceAnchorLink
  },

  mounted() {
    this.$nextTick(function() {
      this.$emit('isReady')
    })
  }
}
</script>
