<template lang="md">
  ## Amazon Forest Dieback

  The Amazon rainforest is the largest tropical rainforest and a center of biodiversity, that is defined by plenty of rainfall, mostly generated by itself. A moist atmosphere is being upheld by high temperatures causing evaporation of local rainfall and transpiration of moisture from plant leaves, basically creating more rainfall.

  The rainforest absorbs great amounts of carbon and cools the global temperature, so that “[e]ven a partial loss of rainforest would substantially increase carbon levels in the atmosphere.” Increasing global temperatures provoke a decrease in rainfall, leading to a reduction in evaporation and ultimately amplifying tropical warming and drying. Additionally transpiration declines as a result of higher CO2 levels that leaves plant pores open less widely, making them lose less water and therefore transferring less water into the atmosphere. Another factor is deforestation, as a decline in trees negatively impacts evaporation and reduces rainfall significantly.

  Eventually all these events entail less fertile soil and result in and/or are caused by tree loss. Continuing the current path of deforestation, a projected trend shows that 40% of Amazon forests will be eliminated by 2050 and result in a vast release of carbon into the atmosphere and drier climate.

  There have already been noticeable consequences like severe droughts in 2005 and 2010 as well as an increase in wildfires. Dry seasons have grown during the past decades and it has been suggested that an excessive dry period represents a tipping point for the Amazon rainforest, turning it into a completely different habitat.

  Many studies consider global warming of 4°C to be needed for most Amazonian regions to turn into savannahs. But research ”[…] shows that even severe cuts in deforestation and carbon emissions will fail to save the emblematic South American jungle […]” and that “[…] the destruction of large parts of the forest is "irreversible"”.
</template>
