<template>
  <div class="content">
    <h2>Legal & Privacy</h2>

    <h3>Liability for Content</h3>
    <p>
      We make every effort to keep the information on this website current, but
      accept no liability whatsoever for the content provided. Pursuant to §7
      par. 1 of TMG (German Tele-Media Act), the law limits our responsibility
      as a service provider to our own content on these Web pages.
    </p>
    <p>
      According to §§8 to 10 of TMG, we are not obligated to monitor third party
      information provided or stored on this website. However, we shall promptly
      remove any content upon becoming aware that it violates the law. Our
      liability in such an instance shall commence at the time we become aware
      of the respective violation.
    </p>

    <h3>Cookies</h3>
    <p>
      Like many other websites, ours also uses so-called »cookies«. Cookies are
      small text files that are transferred from a website server to your hard
      drive. This automatically gives ours certain data, such as IP address,
      browser used, operating system and your connection to the Internet.
    </p>
    <p>
      Cookies can not be used to launch programs or to transfer viruses to a
      computer.
    </p>
    <p>
      In no case will the data collected by us be passed on to third parties or
      a link with personal data will be established without your consent.
    </p>
    <p>
      Of course, you can also view our website without cookies. Internet
      browsers are regularly set to accept cookies. In general, you can disable
      the use of cookies at any time through the settings of your browser.
      Please use the help features of your internet browser to find out how to
      change these settings. Please note that some features of our website may
      not work if you have disabled the use of cookies.
    </p>

    <h3>SSL encryption</h3>
    <p>
      To protect the security of your data during transmission, this website
      uses SSL over HTTPS.
    </p>

    <h3>Adobe Fonts</h3>
    <p>
      This website uses so-called Web fonts, which are provided through the
      Adobe Fonts service of Adobe Systems Incorporated, 345 Park Avenue, San
      Jose, 95110-2704 California, USA (»Adobe Fonts«), for consistent
      presentation of fonts.
    </p>
    <p>
      When you visit a page, your browser loads the required web fonts into its
      browser cache to display texts and fonts correctly. To do this, the
      browser you are using must connect to the Adobe Fonts servers. This gives
      Adobe Fonts knowledge that this website has been accessed via your IP
      address. If your browser does not support web fonts, a default font will
      be used by your computer.
    </p>
    <p>
      The use of Adobe Fonts is in the interest of a uniform and attractive
      presentation of this website. This constitutes a legitimate interest
      within the meaning of §6 par. 1 lit. f GDPR.
    </p>
    <p>
      The privacy policy of Adobe Fonts can be found here:
      <a
        href="https://www.adobe.com/de/privacy/policies/adobe-fonts.html"
        target="_blank"
      >
        <br />
        https://www.adobe.com/de/privacy/policies/adobe-fonts.html
      </a>
    </p>

    <h3>Use of Google Analytics</h3>
    <p>
      This website uses Google Analytics, a web analysis service of Google Inc.
      (following: Google). Google Analytics uses "cookies", which are text files
      placed on your computer, to help the website analyze how users use the
      site. The information generated by the cookie about your use of this
      website is usually transferred to a Google server in the USA and stored
      there. However, due to the activation of IP anonymization on these
      websites, your IP address will be shortened by Google within member states
      of the European Union or in other states which are party to the Agreement
      on the European Economic Area. Only in exceptional cases will the full IP
      address be transferred to a Google server in the USA and shortened there.
      On behalf of the operator of this website, Google will use this
      information for the purpose of evaluating your use of the website,
      compiling reports on website activity and providing other services
      relating to website activity and internet usage. The IP address
      transmitted by your browser within the scope of Google Analytics is not
      combined with other data from Google.
    </p>
    <p>
      The purposes of the data processing are to evaluate the use of the website
      and to compile reports on activities on the website. Based on the use of
      the website and the Internet, further related services will then be
      provided. The processing is based on the legitimate interest of the
      website operator.
    </p>
    <p>
      You may refuse the use of cookies by selecting the appropriate settings on
      your browser, however please note that if you do this you may not be able
      to use the full functionality of this website. You can also prevent the
      collection of data generated by the cookie and related to your use of the
      website (including your IP address) to Google and the processing of this
      data by Google by downloading and installing the browser plugin available
      at the following link:
      <a href="http://tools.google.com/dlpage/gaoptout?hl=de" target="_blank"
        >Browser Add On to deactivate Google Analytics</a
      >.
    </p>
    <p>
      Google is certified under the Privacy Shield Agreement. This is a
      guarantee to comply with the European data protection law: <br /><a
        href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active"
        target="_blank"
        >https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&status=Active</a
      >
    </p>
  </div>
</template>

<script>
export default {
  layout: 'text'
}
</script>
